Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.out_proj.bias', 'classifier.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Map:  69%|██████████████████████████████████▎               | 30000/43780 [00:03<00:01, 8140.90 examples/s]


























































































































































































































































































 10%|██████▌                                                          | 400/4000 [09:34<1:26:13,  1.44s/it]





  File "/data/2_data_server/nlp-04/lost_technology/test.py", line 105, in <module> [00:12<00:00,  2.24it/s]
    trainer.train()
  File "/home/nlp-04/anaconda3/envs/fuck/lib/python3.11/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/nlp-04/anaconda3/envs/fuck/lib/python3.11/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/nlp-04/anaconda3/envs/fuck/lib/python3.11/site-packages/transformers/trainer.py", line 2256, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlp-04/anaconda3/envs/fuck/lib/python3.11/site-packages/transformers/trainer.py", line 2972, in evaluate
    output = eval_loop(
             ^^^^^^^^^^
  File "/home/nlp-04/anaconda3/envs/fuck/lib/python3.11/site-packages/transformers/trainer.py", line 3261, in evaluation_loop
    metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, label_ids=all_labels))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/2_data_server/nlp-04/lost_technology/test.py", line 53, in compute_metrics
    max_probs = np.max(softmax_preds, axis=-1)  # 각 예측에 대한 최대 확률
                ^^
NameError: name 'np' is not defined